version: "3"
services:
    cowsay:
        image: weithenn/faas-cowsay:latest
        labels:
            function: "true"
        networks:
            - functions
        environment:
            no_proxy: "gateway"
            https_proxy: $https_proxy
        deploy:
            placement:
                constraints:
                    - 'node.platform.os == linux'
networks:
    functions:
        driver: overlay
        labels:
          - "openfaas=true"
